version: "3.8"

services:
  app:
    build: .
    container_name: imageapp
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "9999:9999"
    depends_on:
      - mongo
    volumes:
     
      - uploads:/app/uploads

  mongo:
    image: mongo:6.0
    container_name: imageapp-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: imageapp

volumes:
  mongo_data:
  uploads:
